/* model_studio.c generated by valac 0.38.3, the Vala compiler
 * generated from model_studio.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdio.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define MODEL_STUDIO_TYPE_APPLICATION_WINDOW (model_studio_application_window_get_type ())
#define MODEL_STUDIO_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MODEL_STUDIO_TYPE_APPLICATION_WINDOW, ModelStudioApplicationWindow))
#define MODEL_STUDIO_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MODEL_STUDIO_TYPE_APPLICATION_WINDOW, ModelStudioApplicationWindowClass))
#define MODEL_STUDIO_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MODEL_STUDIO_TYPE_APPLICATION_WINDOW))
#define MODEL_STUDIO_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MODEL_STUDIO_TYPE_APPLICATION_WINDOW))
#define MODEL_STUDIO_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MODEL_STUDIO_TYPE_APPLICATION_WINDOW, ModelStudioApplicationWindowClass))

typedef struct _ModelStudioApplicationWindow ModelStudioApplicationWindow;
typedef struct _ModelStudioApplicationWindowClass ModelStudioApplicationWindowClass;
typedef struct _ModelStudioApplicationWindowPrivate ModelStudioApplicationWindowPrivate;
enum  {
	MODEL_STUDIO_APPLICATION_WINDOW_0_PROPERTY,
	MODEL_STUDIO_APPLICATION_WINDOW_NUM_PROPERTIES
};
static GParamSpec* model_studio_application_window_properties[MODEL_STUDIO_APPLICATION_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define MODEL_STUDIO_TYPE_APPLICATION (model_studio_application_get_type ())
#define MODEL_STUDIO_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplication))
#define MODEL_STUDIO_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplicationClass))
#define MODEL_STUDIO_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MODEL_STUDIO_TYPE_APPLICATION))
#define MODEL_STUDIO_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MODEL_STUDIO_TYPE_APPLICATION))
#define MODEL_STUDIO_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplicationClass))

typedef struct _ModelStudioApplication ModelStudioApplication;
typedef struct _ModelStudioApplicationClass ModelStudioApplicationClass;
typedef struct _ModelStudioApplicationPrivate ModelStudioApplicationPrivate;
enum  {
	MODEL_STUDIO_APPLICATION_0_PROPERTY,
	MODEL_STUDIO_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* model_studio_application_properties[MODEL_STUDIO_APPLICATION_NUM_PROPERTIES];

struct _ModelStudioApplicationWindow {
	GtkApplicationWindow parent_instance;
	ModelStudioApplicationWindowPrivate * priv;
	GtkBox* main_box;
};

struct _ModelStudioApplicationWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _ModelStudioApplication {
	GtkApplication parent_instance;
	ModelStudioApplicationPrivate * priv;
};

struct _ModelStudioApplicationClass {
	GtkApplicationClass parent_class;
};

struct _ModelStudioApplicationPrivate {
	ModelStudioApplicationWindow* application_window;
};


static gpointer model_studio_application_window_parent_class = NULL;
static gpointer model_studio_application_parent_class = NULL;

GType model_studio_application_window_get_type (void) G_GNUC_CONST;
ModelStudioApplicationWindow* model_studio_application_window_new (GtkApplication* application);
ModelStudioApplicationWindow* model_studio_application_window_construct (GType object_type, GtkApplication* application);
static void model_studio_application_window_finalize (GObject * obj);
GType model_studio_application_get_type (void) G_GNUC_CONST;
#define MODEL_STUDIO_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplicationPrivate))
void model_studio_application_on_startup (ModelStudioApplication* self);
void model_studio_application_on_application_window_destroy (ModelStudioApplication* self);
static void _model_studio_application_on_application_window_destroy_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
void model_studio_application_on_activate (ModelStudioApplication* self);
ModelStudioApplication* model_studio_application_new (void);
ModelStudioApplication* model_studio_application_construct (GType object_type);
static GObject * model_studio_application_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _model_studio_application_on_startup_g_application_startup (GApplication* _sender, gpointer self);
static void _model_studio_application_on_activate_g_application_activate (GApplication* _sender, gpointer self);
static void model_studio_application_finalize (GObject * obj);
gint model_studio_main (gchar** args, int args_length1);


ModelStudioApplicationWindow* model_studio_application_window_construct (GType object_type, GtkApplication* application) {
	ModelStudioApplicationWindow * self = NULL;
	GtkApplication* _tmp0_;
	g_return_val_if_fail (application != NULL, NULL);
	_tmp0_ = application;
	self = (ModelStudioApplicationWindow*) g_object_new (object_type, "application", _tmp0_, NULL);
	return self;
}


ModelStudioApplicationWindow* model_studio_application_window_new (GtkApplication* application) {
	return model_studio_application_window_construct (MODEL_STUDIO_TYPE_APPLICATION_WINDOW, application);
}


static void model_studio_application_window_class_init (ModelStudioApplicationWindowClass * klass) {
	model_studio_application_window_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = model_studio_application_window_finalize;
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/org/gtk/icc/model-studio/application_window.glade");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "main_box", FALSE, G_STRUCT_OFFSET (ModelStudioApplicationWindow, main_box));
}


static void model_studio_application_window_instance_init (ModelStudioApplicationWindow * self) {
	gtk_widget_init_template (GTK_WIDGET (self));
}


static void model_studio_application_window_finalize (GObject * obj) {
	ModelStudioApplicationWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MODEL_STUDIO_TYPE_APPLICATION_WINDOW, ModelStudioApplicationWindow);
	_g_object_unref0 (self->main_box);
	G_OBJECT_CLASS (model_studio_application_window_parent_class)->finalize (obj);
}


GType model_studio_application_window_get_type (void) {
	static volatile gsize model_studio_application_window_type_id__volatile = 0;
	if (g_once_init_enter (&model_studio_application_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ModelStudioApplicationWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) model_studio_application_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ModelStudioApplicationWindow), 0, (GInstanceInitFunc) model_studio_application_window_instance_init, NULL };
		GType model_studio_application_window_type_id;
		model_studio_application_window_type_id = g_type_register_static (gtk_application_window_get_type (), "ModelStudioApplicationWindow", &g_define_type_info, 0);
		g_once_init_leave (&model_studio_application_window_type_id__volatile, model_studio_application_window_type_id);
	}
	return model_studio_application_window_type_id__volatile;
}


static void _model_studio_application_on_application_window_destroy_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	model_studio_application_on_application_window_destroy ((ModelStudioApplication*) self);
}


void model_studio_application_on_startup (ModelStudioApplication* self) {
	FILE* _tmp0_;
	ModelStudioApplicationWindow* _tmp1_;
	ModelStudioApplicationWindow* _tmp2_;
	ModelStudioApplicationWindow* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fputs ("Startup of ModelStudio\n", _tmp0_);
	_tmp1_ = model_studio_application_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->application_window);
	self->priv->application_window = _tmp1_;
	_tmp2_ = self->priv->application_window;
	g_signal_connect_object ((GtkWidget*) _tmp2_, "destroy", (GCallback) _model_studio_application_on_application_window_destroy_gtk_widget_destroy, self, 0);
	_tmp3_ = self->priv->application_window;
	gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) _tmp3_);
}


void model_studio_application_on_activate (ModelStudioApplication* self) {
	ModelStudioApplicationWindow* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->application_window;
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
}


void model_studio_application_on_application_window_destroy (ModelStudioApplication* self) {
	g_return_if_fail (self != NULL);
	g_application_quit ((GApplication*) self);
}


ModelStudioApplication* model_studio_application_construct (GType object_type) {
	ModelStudioApplication * self = NULL;
	self = (ModelStudioApplication*) g_object_new (object_type, NULL);
	return self;
}


ModelStudioApplication* model_studio_application_new (void) {
	return model_studio_application_construct (MODEL_STUDIO_TYPE_APPLICATION);
}


static void _model_studio_application_on_startup_g_application_startup (GApplication* _sender, gpointer self) {
	model_studio_application_on_startup ((ModelStudioApplication*) self);
}


static void _model_studio_application_on_activate_g_application_activate (GApplication* _sender, gpointer self) {
	model_studio_application_on_activate ((ModelStudioApplication*) self);
}


static GObject * model_studio_application_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ModelStudioApplication * self;
	parent_class = G_OBJECT_CLASS (model_studio_application_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplication);
	g_signal_connect_object ((GApplication*) self, "startup", (GCallback) _model_studio_application_on_startup_g_application_startup, self, 0);
	g_signal_connect_object ((GApplication*) self, "activate", (GCallback) _model_studio_application_on_activate_g_application_activate, self, 0);
	return obj;
}


static void model_studio_application_class_init (ModelStudioApplicationClass * klass) {
	model_studio_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ModelStudioApplicationPrivate));
	G_OBJECT_CLASS (klass)->constructor = model_studio_application_constructor;
	G_OBJECT_CLASS (klass)->finalize = model_studio_application_finalize;
}


static void model_studio_application_instance_init (ModelStudioApplication * self) {
	self->priv = MODEL_STUDIO_APPLICATION_GET_PRIVATE (self);
}


static void model_studio_application_finalize (GObject * obj) {
	ModelStudioApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplication);
	_g_object_unref0 (self->priv->application_window);
	G_OBJECT_CLASS (model_studio_application_parent_class)->finalize (obj);
}


GType model_studio_application_get_type (void) {
	static volatile gsize model_studio_application_type_id__volatile = 0;
	if (g_once_init_enter (&model_studio_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ModelStudioApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) model_studio_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ModelStudioApplication), 0, (GInstanceInitFunc) model_studio_application_instance_init, NULL };
		GType model_studio_application_type_id;
		model_studio_application_type_id = g_type_register_static (gtk_application_get_type (), "ModelStudioApplication", &g_define_type_info, 0);
		g_once_init_leave (&model_studio_application_type_id__volatile, model_studio_application_type_id);
	}
	return model_studio_application_type_id__volatile;
}


gint model_studio_main (gchar** args, int args_length1) {
	gint result = 0;
	ModelStudioApplication* app = NULL;
	ModelStudioApplication* _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_;
	_tmp0_ = model_studio_application_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = _tmp2_;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	return model_studio_main (argv, argc);
}



