/* model_studio.c generated by valac 0.38.3, the Vala compiler
 * generated from model_studio.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "icc_gui.h"
#include <gio/gio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#define MODEL_STUDIO_TYPE_APPLICATION (model_studio_application_get_type ())
#define MODEL_STUDIO_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplication))
#define MODEL_STUDIO_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplicationClass))
#define MODEL_STUDIO_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MODEL_STUDIO_TYPE_APPLICATION))
#define MODEL_STUDIO_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MODEL_STUDIO_TYPE_APPLICATION))
#define MODEL_STUDIO_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MODEL_STUDIO_TYPE_APPLICATION, ModelStudioApplicationClass))

typedef struct _ModelStudioApplication ModelStudioApplication;
typedef struct _ModelStudioApplicationClass ModelStudioApplicationClass;
typedef struct _ModelStudioApplicationPrivate ModelStudioApplicationPrivate;
enum  {
	MODEL_STUDIO_APPLICATION_0_PROPERTY,
	MODEL_STUDIO_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* model_studio_application_properties[MODEL_STUDIO_APPLICATION_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ModelStudioApplication {
	IccGuiApplication parent_instance;
	ModelStudioApplicationPrivate * priv;
};

struct _ModelStudioApplicationClass {
	IccGuiApplicationClass parent_class;
};


static gpointer model_studio_application_parent_class = NULL;

GType model_studio_application_get_type (void) G_GNUC_CONST;
ModelStudioApplication* model_studio_application_new (void);
ModelStudioApplication* model_studio_application_construct (GType object_type);
void model_studio_application_on_startup (ModelStudioApplication* self);
static void _model_studio_application_on_startup_g_application_startup (GApplication* _sender, gpointer self);
gint model_studio_main (gchar** args, int args_length1);


static void _model_studio_application_on_startup_g_application_startup (GApplication* _sender, gpointer self) {
	model_studio_application_on_startup ((ModelStudioApplication*) self);
}


ModelStudioApplication* model_studio_application_construct (GType object_type) {
	ModelStudioApplication * self = NULL;
	self = (ModelStudioApplication*) icc_gui_application_construct (object_type, NULL, 0, "../ui/application_window.glade");
	g_signal_connect_object ((GApplication*) self, "startup", (GCallback) _model_studio_application_on_startup_g_application_startup, self, 0);
	return self;
}


ModelStudioApplication* model_studio_application_new (void) {
	return model_studio_application_construct (MODEL_STUDIO_TYPE_APPLICATION);
}


void model_studio_application_on_startup (ModelStudioApplication* self) {
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fputs ("Startup of ModelStudio\n", _tmp0_);
}


static void model_studio_application_class_init (ModelStudioApplicationClass * klass) {
	model_studio_application_parent_class = g_type_class_peek_parent (klass);
}


static void model_studio_application_instance_init (ModelStudioApplication * self) {
}


GType model_studio_application_get_type (void) {
	static volatile gsize model_studio_application_type_id__volatile = 0;
	if (g_once_init_enter (&model_studio_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ModelStudioApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) model_studio_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ModelStudioApplication), 0, (GInstanceInitFunc) model_studio_application_instance_init, NULL };
		GType model_studio_application_type_id;
		model_studio_application_type_id = g_type_register_static (ICC_GUI_TYPE_APPLICATION, "ModelStudioApplication", &g_define_type_info, 0);
		g_once_init_leave (&model_studio_application_type_id__volatile, model_studio_application_type_id);
	}
	return model_studio_application_type_id__volatile;
}


gint model_studio_main (gchar** args, int args_length1) {
	gint result = 0;
	ModelStudioApplication* app = NULL;
	ModelStudioApplication* _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_;
	_tmp0_ = model_studio_application_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = _tmp2_;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	return model_studio_main (argv, argc);
}



